# -*- coding: utf-8 -*-
"""svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxwbOXYLvgBlzLAuGnvAhM23FLLQCcJN

https://colab.research.google.com/drive/1VxwbOXYLvgBlzLAuGnvAhM23FLLQCcJN?authuser=1#scrollTo=n4uOc2Pdc3WU

# Machine Learning Exercise - Support Vector Machines
The idea of this exercise is to use support vector machines (SVMs) to build a spam classifier.  
We'll start with SVMs on some 2D data sets.  Then we'll do some pre-processing work on a set of raw emails and build a classifier using a SVM to determine if they are spam or not.
1) Load the dataset "session12_data1.mat". Explore the data and see how a linear SVM works on the data set for several values of C. Start from C=1. Compare the results and look at the confidence level for each class prediction. Comment the results.
2) Move from a linear SVM to one that's capable of non-linear classification using kernels. Test the gaussian kernel function. Comment the results.
3) Examine another data set, this time with a non-linear decision boundary: "session12_data2.mat". Explore the data and use a Gaussian kernel with the SVM for classification. Comment the results.
4) Load the third data set "session12_data3.mat". Here we have training and validation sets and our task is to use the cross validation set to determine the best C and σ parameter to use, based on validation set performance.
5) Finally, we implement a spam classifier with a SVM. Use the data "session12_spamTrain.mat" and "session12_spamTest.mat".

### This part of the code only deals with finding and importing the files, not important to look at in depth
"""

# === 0) Imports ===
import os, glob
import numpy as np
import matplotlib.pyplot as plt
import scipy.io as sio
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn import svm

# === 1) Mount Drive ===
from google.colab import drive
drive.mount('/content/drive')

# === 2) Find the MAT file anywhere in Drive (change the pattern if needed) ===
# Try to find something like "...data1... .mat"
candidates = glob.glob('/content/drive/MyDrive/**/*.mat', recursive=True)
print("All .mat files I can see:\n", "\n".join(candidates) or "(none)")

# Prefer a file that contains "data1" in the name
mat_files = [p for p in candidates if 'data1' in os.path.basename(p).lower()]
if not mat_files:
    raise FileNotFoundError(
        "I couldn't find any *.mat with 'data1' in its name under MyDrive. "
        "Either move the file into MyDrive or adjust the search pattern above."
    )

MAT_PATH = mat_files[0]
print("\nUsing MAT file:", MAT_PATH)

# === 3) Load the MAT file (robust) ===
mat = sio.loadmat(MAT_PATH, squeeze_me=True, struct_as_record=False, simplify_cells=True)
print("\nTop-level keys:", [k for k in mat.keys() if not k.startswith('__')])

# Try common key names for X and y
for xk in ['X','x','X1','features','Xdata']:
    if xk in mat:
        X = np.asarray(mat[xk], dtype=float)
        break
else:
    raise KeyError("Couldn't find feature matrix. Keys were: " + str([k for k in mat.keys() if not k.startswith('__')]))

for yk in ['y','Y','label','labels','target']:
    if yk in mat:
        y = np.asarray(mat[yk]).ravel()
        break
else:
    raise KeyError("Couldn't find label vector. Keys were: " + str([k for k in mat.keys() if not k.startswith('__')]))

print(f"X shape: {X.shape} | y shape: {y.shape} | unique y: {np.unique(y)}")

"""# 1: Explore the data and see how a linear SVM works on the data set for several values of C

### Quick plot (expects 2 features)
"""

if X.ndim == 2 and X.shape[1] == 2:
    pos = (y == 1) #Defines “positive” points as label 1.
    neg = (y == 0) | (y == -1) #Defines “negative” points as label 0 or -1 (different datasets use different encodings).
    plt.figure(figsize=(5,5))
    plt.scatter(X[pos,0], X[pos,1], label='Positive (1)', alpha=0.8)
    plt.scatter(X[neg,0], X[neg,1], label='Negative (0/-1)', alpha=0.8)
    plt.legend(); plt.title("Dataset 1 Visual Exploration"); plt.xlabel("x1"); plt.ylabel("x2")
    plt.tight_layout(); plt.show()
else:
    print("Note: X is not 2-D with two columns, so I’m skipping the scatter plot.") # Only builds the plot if there are exactly two features (so I can do a 2D scatter).

"""**Interpretation: this plot is just a sanity check, it lets me see the extent to which the points are linearly separable (they look like they are)**

What 0 and 1 represent:
- They’re the class labels. In a 2-class problem we typically encode classes as 0 and 1.
- For the spam dataset:
  - 1 = spam
  - 0 = ham (not spam)
- Some .mat bundles use -1 instead of 0 for the negative class; that’s why the code treats negatives as (y == 0) | (y == -1).

NOTE: C is a regularisation parameter.
"""

from sklearn import svm, metrics
import numpy as np
import matplotlib.pyplot as plt

#helper for plotting 2D boundaries (only plots if there's exactly 2 features, to draw a 2D boundary)
def plot_boundary(X, y, clf, title):
    if X.shape[1] != 2:
        print(f"(skip plot: X has {X.shape[1]} features)")
        return
    x1min, x1max = X[:,0].min()-0.5, X[:,0].max()+0.5
    x2min, x2max = X[:,1].min()-0.5, X[:,1].max()+0.5
    xx, yy = np.meshgrid(np.linspace(x1min, x1max, 400),
                         np.linspace(x2min, x2max, 400))
    Z = clf.decision_function(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape) # For each grid point, compute the decision score of the trained SVM.
    #decision_function > 0 ⇒ class 1; < 0 ⇒ class 0.
    #np.c_[...] stacks the flattened grid coords into an N×2 array; then reshape back to the grid.

    plt.figure(figsize=(5,5))
    plt.contourf(xx, yy, Z>0, alpha=0.15)
    plt.contour(xx, yy, Z, levels=[-1,0,1], linestyles=['--','-','--']) #Draw the classic SVM lines: Z=0 (solid) is the decision boundary. Z=±1 (dashed) are the margins.
    plt.scatter(X[y==1,0], X[y==1,1], s=20, label='Pos')
    plt.scatter(X[y!=1,0], X[y!=1,1], s=20, label='Neg')
    plt.title(title); plt.legend(); plt.show()

X1, y1 = X, y.astype(int)

for C in [0.01, 0.1, 1, 10, 100]: #Loop over different regularization strengths: Small C → stronger regularization → wider margin, allow more training errors (higher bias).
#Large C → weaker regularization → tighter fit to training data (lower bias, higher variance).

    clf = make_pipeline(StandardScaler(), svm.SVC(C=C, kernel='linear')) #STANDARD SCALER because we're dealing with distances. It's a linear model so we use kernel = linear.
    clf.fit(X1, y1) #Train the SVM on the dataset.
    scores = clf.decision_function(X1) # Get each point’s signed distance to the decision boundary. Larger |score| ≈ higher confidence in the prediction; sign gives the class.
    acc = clf.score(X1, y1)
    print(f"Linear SVM (C={C}) — acc={acc:.3f} | |score| mean={np.abs(scores).mean():.3f} median={np.median(np.abs(scores)):.3f}")
    plot_boundary(X1, y1, clf, f"Dataset 1 — Linear (C={C})")

"""#Interpretation

## C = 0.01 — acc ≈ 0.64 (underfitting)
- Very small C = strong regularization. The model prefers a very wide/soft margin and is happy to misclassify many points.

## C = 0.1 — acc ≈ 0.98
- Regularization is relaxed a bit. The boundary now aligns with the visible separation.
- Only ~1–2 training points near the overlap/margin are misclassified.
- Confidence (|score|) rises: most points lie farther from the boundary.

## C = 1 — acc ≈ 0.98
- Similar boundary to C=0.1, still general-looking and stable.
- Slight increase in |score|, meaning the classifier is pushing points a bit further away from the boundary (on the training set).

## C = 10 — acc ≈ 0.98
- Boundary nudges a little closer to perfectly separating the data.
- Even larger |score|: the model fits the training set more tightly.

##C = 100 — acc = 1.00 (near hard-margin fit)
- Very weak regularization: the model is trying to separate perfectly.
- Zero training errors; |score| jumps—predictions are very confident on the training set.


# Bias–variance trade-off:
- **Tiny C (0.01)** → high bias, underfits.
- **Moderate C (0.1–1)** → good fit with a clean, stable boundary.
- **Large C (10–100)** → pushes toward a hard separation; great training accuracy, but with more risk of overfitting in noisier settings.

# Support Vectors:
"""

import numpy as np
from sklearn import svm

results = []

for C in [0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30, 100]:
    clf = make_pipeline(StandardScaler(), svm.SVC(C=C, kernel='linear'))
    clf.fit(X1, y1)

    # Basic counts
    n_total = X1.shape[0]
    n_sv_total = clf.support_.size              # total support vectors
    n_sv_by_class = clf.n_support_              # [n_neg, n_pos] typically
    frac_sv = n_sv_total / n_total

    # Margin status of the support vectors
    scores_sv = clf.decision_function(X1[clf.support_])
    # In theory: |score| = 1 -> exactly on margin; <1 -> inside margin (slack)
    on_margin = np.isclose(np.abs(scores_sv), 1.0, atol=1e-6).sum()
    inside_margin = (np.abs(scores_sv) < 1 - 1e-6).sum()  # slack violators

    acc = clf.score(X1, y1)

    results.append({
        "C": C,
        "acc": acc,
        "n_sv_total": int(n_sv_total),
        "n_sv_neg": int(n_sv_by_class[0]),
        "n_sv_pos": int(n_sv_by_class[1]),
        "frac_sv": frac_sv,
        "on_margin": int(on_margin),
        "inside_margin": int(inside_margin),
    })

# Pretty print
print(f"{'C':>6}  {'acc':>6}  {'SVs':>5}  {'neg':>4}  {'pos':>4}  {'SV%':>6}  {'on|margin':>10}  {'inside':>6}")
for r in results:
    print(f"{r['C']:>6}  {r['acc']:>6.3f}  {r['n_sv_total']:>5}  {r['n_sv_neg']:>4}  {r['n_sv_pos']:>4}  "
          f"{100*r['frac_sv']:>5.1f}%  {r['on_margin']:>10}  {r['inside_margin']:>6}")

import matplotlib.pyplot as plt

Cs = [r["C"] for r in results]
frac = [r["frac_sv"] for r in results]

plt.figure(figsize=(5,3.2))
plt.plot(Cs, frac, marker='o')
plt.xscale('log')
plt.xlabel("C (log scale)")
plt.ylabel("Fraction of support vectors")
plt.title("How many points define the boundary vs. C")
plt.tight_layout()
plt.show()

"""## How to read this

- SVs (support vectors): training points that lie on or inside the margin. They are the only points that affect the learned hyperplane.

- on_margin: |score| ≈ 1 → exactly on the margin.

- inside: |score| < 1 → margin violators (slack) — either misclassified or correctly classified but within the margin.

Trend you’ll usually see:

- As C increases, the model penalizes violations more → it pushes to separate harder → typically fewer support vectors overall, and fewer inside-margin violators.

- As C decreases (strong regularization), the margin gets “softer” → more points become support vectors, with more violators, and accuracy can drop (underfitting).

# 2: Move from a linear SVM to one that's capable of non-linear classification using kernels. Test the gaussian kernel function. Comment the results.

Note:
- Smaller σ ⇒ larger γ ⇒ very narrow kernels (highly local influence).
- Larger σ ⇒ smaller γ ⇒ wide kernels (smoother influence).

γ = = 1/2σ^2
"""

for sigma in [0.1, 0.3, 1, 3]:
    gamma = 1/(2*sigma**2)
    clf = make_pipeline(StandardScaler(), svm.SVC(C=1, kernel='rbf', gamma=gamma)) #Higher C = fit harder to the training set; lower C = more regularization. I held C=1 fixed and varied σ, so I'm mostly changing the shape/complexity of the decision boundary.
    clf.fit(X1, y1)
    print(f"RBF SVM (C=1, σ={sigma}) — acc={clf.score(X1, y1):.3f}")
    plot_boundary(X1, y1, clf, f"Dataset 1 — RBF (σ={sigma})")

"""# Interpretation:

How σ affects the boundary (intuition):
- Small σ (e.g., 0.1): boundary can wiggle a lot to fit local patterns → risk of overfitting.
- Medium σ (e.g., 0.3–1): often a good balance—captures mild curvature without chasing noise.
- Large σ (e.g., 3): boundary becomes almost linear / very smooth → risk of underfitting.


#Reading each panel:

** σ = 0.1 (γ large) ** — very wiggly, acc = 1.00
- Tiny σ ⇒ kernels are very local.
- Boundary forms many little “islands” tightly wrapping individual points.
- Fits every training point (perfect acc) but is high-variance / overfit; extremely sensitive to noise/outliers.
- Will likely generalize worse than it looks here.

** σ = 0.3 ** — smooth but flexible, acc = 1.00
- Wider kernels ⇒ nearby points are blended over a broader area.
- Boundary still captures mild curvature but stops chasing single points.
- This looks like a good bias–variance balance for this dataset.

** σ = 1 ** — even smoother, acc = 1.00
- Decision regions are now large, gently curved blobs separating the two clusters.
- Still classifies the training set perfectly, but with a much simpler boundary than σ=0.1.
- Likely best generalization among the four.

** σ = 3 (γ small) ** — almost linear, acc ≈ 0.98
- Kernels are so wide that the RBF behaves close to a linear separator.
- Boundary is very smooth (low variance) but starts to underfit slightly (a couple of training errors).
- If the true relationship were more curved, you’d lose performance faster here.

# What this tells us

- σ controls complexity: small σ ⇒ complex, wiggly boundaries; large σ ⇒ smoother, simpler boundaries.

- Training accuracy is misleading: σ=0.1, 0.3, 1 all give 1.00 on train, but σ=0.1 is clearly overfitting. Use a validation set (like Dataset 3) to choose σ (and C).

- For this dataset (almost linearly separable), σ in ~[0.3, 1] looks healthiest: simple boundary, perfect train fit, likely best test performance.

- C and σ interact: you fixed C=1. If you increased C, even σ=3 might separate perfectly; if you decreased C, σ=0.3/1 might start to miss a few points. Always tune C × σ together.

# 3: Examine another data set, this time with a non-linear decision boundary: "session12_data2.mat". Explore the data and use a Gaussian kernel with the SVM for classification. Comment the results.
"""

# 1) Find and load session12_data2.mat
candidates = glob.glob('/content/drive/MyDrive/**/*.mat', recursive=True)
mat2_files = [p for p in candidates if 'data2' in os.path.basename(p).lower()]
if not mat2_files:
    raise FileNotFoundError("Couldn't find a *.mat with 'data2' in the name.")
MAT2_PATH = mat2_files[0]
print("Using dataset 2:", MAT2_PATH)

mat2 = sio.loadmat(MAT2_PATH, squeeze_me=True, struct_as_record=False, simplify_cells=True)

# extract X2, y2 (same key search logic)
for xk in ['X','x','X1','features','Xdata']:
    if xk in mat2:
        X2 = np.asarray(mat2[xk], dtype=float); break
else:
    raise KeyError("data2: couldn't find features matrix.")

for yk in ['y','Y','label','labels','target']:
    if yk in mat2:
        y2 = np.asarray(mat2[yk]).ravel().astype(int); break
else:
    raise KeyError("data2: couldn't find label vector.")

# 2) Small grid over (C, σ)
best_clf, best_acc, best_params = None, -1, None
for C in [0.1, 1, 10]:
    for sigma in [0.1, 0.3, 1, 3]:
        clf = make_pipeline(StandardScaler(), svm.SVC(C=C, kernel='rbf', gamma=1/(2*sigma**2)))
        clf.fit(X2, y2)
        acc = clf.score(X2, y2)
        print(f"RBF (C={C}, σ={sigma}) — acc={acc:.3f}")
        if acc > best_acc:
            best_acc, best_params, best_clf = acc, (C, sigma), clf

print(f"Best on Dataset 2: C={best_params[0]}, σ={best_params[1]}, acc={best_acc:.3f}")
plot_boundary(X2, y2, best_clf, f"Dataset 2 — Best RBF (C={best_params[0]}, σ={best_params[1]})")

"""# Interpretation:

What I did: used the kernel trick to work in an implicit, very high- (in fact infinite-) dimensional feature space.


Best (the one pictured above): C=10, σ=0.1, acc≈1.
That combo gives a very flexible boundary (small σ → high complexity) plus stronger penalty for violations (larger C), which fits this highly non-linear dataset tightly. It’s great on training data, but higher variance—on a separate test/val split it may or may not be optimal.

#4: Load the third data set "session12_data3.mat". Here we have training and validation sets and our task is to use the cross validation set to determine the best C and σ parameter to use, based on validation set performance.


## What the code does:

- Load the data from session_12_data3.mat
  - X3, y3 = training data
  - X3v, y3v = validation data
- Try many settings of the model:
  - Loop over a grid of values for C (how hard we try to fit the data) and σ (how wiggly/smooth the boundary is for the RBF kernel).
- Train on training set only, then
  - Evaluate on the validation set (compute accuracy).
- Pick the pair (C, σ) with the highest validation accuracy.
  - That’s the “best” model because it should generalize better, not just memorize the training data.
- Plot the best model (since this dataset is 2-D):
  - Solid green line = decision boundary between classes.
  - Dashed purple/yellow lines = SVM margins (the ±1 contours).
  - Shaded regions = which side of the boundary the model predicts.

What the run showed:

- Best by validation was C = 1, σ = 0.1, with about 96.5% accuracy on the validation set.

- The boundary is curved (because RBF kernel) and cleanly separates most points without being overly wiggly—good balance between underfitting and overfitting.

- Why this matters:
  - I tuned the SVM so it performs well on new data, not just the training points—this is the point of using a validation set and doing a grid search over hyperparameters.
"""

# ==== DATASET 3 (uses session_12_data3.mat) ====
import os, numpy as np, scipy.io as sio
from sklearn import svm

# 1) Pick the exact file
try:
    MAT3_PATH = [p for p in candidates if os.path.basename(p).lower() == 'session_12_data3.mat'][0]
except IndexError:
    # Fallback if it's in the root of MyDrive
    MAT3_PATH = '/content/drive/MyDrive/session_12_data3.mat'
print("Using dataset 3:", MAT3_PATH)

# 2) Load
mat3 = sio.loadmat(MAT3_PATH, squeeze_me=True, struct_as_record=False, simplify_cells=True)

# Expect keys: X, y, Xval, yval (with simple fallbacks)
def grab(m, keys):
    for k in keys:
        if k in m: return np.asarray(m[k])
    raise KeyError(f"Missing one of {keys} in {MAT3_PATH}. Keys: {[k for k in m.keys() if not k.startswith('__')]}")

X3   = grab(mat3, ('X','Xtrain','X_train'))
y3   = grab(mat3, ('y','ytrain','y_train')).ravel().astype(int)
X3v  = grab(mat3, ('Xval','X_val','Xcv','X_valid','Xvalid'))
y3v  = grab(mat3, ('yval','y_val','ycv','y_valid','yvalid')).ravel().astype(int)

print("Dataset 3 shapes:", X3.shape, y3.shape, X3v.shape, y3v.shape)


#ACTUAL CODE TO ANSWER QUESTION:

# 3) Grid search over C and sigma
C_vals = [0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30]
sigmas = [0.01, 0.03, 0.1, 0.3, 1, 3, 10]
best_acc, best_params, best_clf = -1, None, None

for C in C_vals:
    for s in sigmas:
        clf = svm.SVC(C=C, kernel='rbf', gamma=1/(2*s**2))
        clf.fit(X3, y3)
        acc = clf.score(X3v, y3v)
        if acc > best_acc:
            best_acc, best_params, best_clf = acc, (C, s), clf

print(f"Best by validation: C={best_params[0]}, σ={best_params[1]}, val acc={best_acc:.3f}")

# 4) Plot (only if 2D)
try:
    def plot_boundary(X, y, clf, title):
        import matplotlib.pyplot as plt, numpy as np
        if X.shape[1] != 2:
            print(f"(skip plot: X has {X.shape[1]} features)")
            return
        x1min, x1max = X[:,0].min()-0.5, X[:,0].max()+0.5
        x2min, x2max = X[:,1].min()-0.5, X[:,1].max()+0.5
        xx, yy = np.meshgrid(np.linspace(x1min, x1max, 400),
                             np.linspace(x2min, x2max, 400))
        Z = clf.decision_function(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)
        plt.figure(figsize=(5,5))
        plt.contourf(xx, yy, Z>0, alpha=0.15)
        plt.contour(xx, yy, Z, levels=[-1,0,1], linestyles=['--','-','--'])
        plt.scatter(X[y==1,0], X[y==1,1], s=20, label='Pos')
        plt.scatter(X[y!=1,0], X[y!=1,1], s=20, label='Neg')
        plt.title(title); plt.legend(); plt.show()

    plot_boundary(X3, y3, best_clf, f"Dataset 3 — Best RBF (C={best_params[0]}, σ={best_params[1]})")
except Exception as e:
    print("(plot skipped)", e)

"""#Interpretation:
Best by validation: C=1, σ=0.1, val acc ≈ 0.965.

σ=0.1 → reasonably flexible RBF (can curve), but not so tiny that it wiggles around every point.

C=1 → moderate regularization: balances margin width vs. violations.

The plot shows a curved boundary that wraps the orange cluster without over-segmenting (good bias–variance balance).

The dashed ±1 curves pass near many boundary points → those are support vectors (points on/inside the margin driving the solution).

In math terms, you just did model selection for a kernel SVM: you chose
(
𝐶
,
𝜎
)
(C,σ) to minimize validation error, i.e., approximate generalization risk rather than training error (which could overfit).
"""

from sklearn.metrics import confusion_matrix, classification_report

print("Train acc:", best_clf.score(X3, y3))
print("Val   acc:", best_clf.score(X3v, y3v))

yhat_val = best_clf.predict(X3v)
print("Confusion matrix (val):\n", confusion_matrix(y3v, yhat_val))
print(classification_report(y3v, yhat_val, digits=3))

print("Support vectors by class:", best_clf.n_support_, "| total:", best_clf.support_.size)

"""# 5) Finally, we implement a spam classifier with a SVM. Use the data "session12_spamTrain.mat" and "session12_spamTest.mat".


The code: trains a linear SVM on the spam training data, evaluates accuracy on both train and test, prints a detailed precision/recall/F1 classification report, shows a confusion matrix (counts and normalized), and optionally lists the most spammy features according to the learned weights. This gives you both a headline score and a granular view of the kinds of mistakes the model makes (false positives vs. false negatives).
"""

# Find the real paths, then load and train the spam SVM

import glob, os, scipy.io as sio, numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix

# 1) Find exact files anywhere under MyDrive
candidates = glob.glob('/content/drive/MyDrive/**/*.mat', recursive=True)

def find_one(name_snippet):
    picks = [p for p in candidates if name_snippet in os.path.basename(p).lower()]
    if not picks:
        raise FileNotFoundError(f"Couldn't find a .mat file containing '{name_snippet}' in its name.")
    return picks[0]

SPAM_TR_PATH = find_one('spamtrain')
SPAM_TE_PATH = find_one('spamtest')

print("Using spamTrain:", SPAM_TR_PATH)
print("Using spamTest :", SPAM_TE_PATH)

# 2) Sanity check
assert os.path.exists(SPAM_TR_PATH), f"Not found: {SPAM_TR_PATH}"
assert os.path.exists(SPAM_TE_PATH), f"Not found: {SPAM_TE_PATH}"

# 3) Load
spam_tr = sio.loadmat(SPAM_TR_PATH, squeeze_me=True, struct_as_record=False, simplify_cells=True)
spam_te = sio.loadmat(SPAM_TE_PATH, squeeze_me=True, struct_as_record=False, simplify_cells=True)

Xtr = np.asarray(spam_tr.get('X', spam_tr.get('Xtrain')), dtype=float)
ytr = np.asarray(spam_tr.get('y', spam_tr.get('ytrain'))).ravel().astype(int)
Xte = np.asarray(spam_te.get('Xtest', spam_te.get('X')), dtype=float)
yte = np.asarray(spam_te.get('ytest', spam_te.get('y'))).ravel().astype(int)

print("Shapes — train:", Xtr.shape, ytr.shape, "| test:", Xte.shape, yte.shape)

# 4) Train + evaluate a linear SVM (standard for spam)
clf = svm.SVC(C=0.1, kernel='linear') #linear because we're building a linear classifier. For SPAM, the decision surface is usually close to linear in the high-dimensional feature space, so a linear kernel is fast, strong, and standard.
clf.fit(Xtr, ytr) # Learns the separating hyperplane from the training data: the weight vector w (one weight per feature) and bias b.

print("\nTraining accuracy:", clf.score(Xtr, ytr)) #score = accuracy. You check train (did we fit the data?) and test (does it generalize to unseen emails?).
print("Test accuracy    :", clf.score(Xte, yte))

yhat = clf.predict(Xte) #Produces 0/1 labels (typically 0=ham, 1=spam) for each test email.
print("\nClassification report:\n", classification_report(yte, yhat, digits=3))
cm = confusion_matrix(yte, yhat)
print("Confusion matrix:\n", cm)

# ----- Visual confusion matrices -----
labels = np.unique(np.concatenate([yte, yhat]))  # typically [0,1]
ticklabels = ['Ham' if l==0 else 'Spam' for l in labels]

def plot_cm(matrix, title, fmt='d'):
    fig, ax = plt.subplots(figsize=(4.8, 4))
    im = ax.imshow(matrix, interpolation='nearest')
    ax.figure.colorbar(im, ax=ax)
    ax.set(xticks=np.arange(len(labels)), yticks=np.arange(len(labels)),
           xticklabels=ticklabels, yticklabels=ticklabels,
           xlabel='Predicted label', ylabel='True label', title=title)
    thresh = matrix.max() / 2.0
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            ax.text(j, i, format(matrix[i, j], fmt),
                    ha='center', va='center',
                    color='white' if matrix[i, j] > thresh else 'black')
    plt.tight_layout(); plt.show()

# Raw counts
plot_cm(cm, 'Confusion Matrix (Counts)', fmt='d')

# Row-normalized
cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
plot_cm(np.round(cm_norm, 2), 'Confusion Matrix (Row-Normalized)', fmt='.2f')

# Optional: top-weighted features
if hasattr(clf, "coef_"):
    w = clf.coef_.ravel()
    top_idx = np.argsort(w)[-20:][::-1]
    print("\nTop 20 feature indices for spam:", top_idx.tolist())

"""# Interpretation

Training accuracy: 0.998

Test accuracy: 0.989 → excellent generalization.

Class distribution (test): 692 ham (0), 308 spam (1).

Confusion matrix (counts):
- TN=684 ham correctly kept as ham
- FP=8 ham incorrectly flagged as spam
- FN=3 spam missed (labeled ham)
- TP=305 spam correctly caught

Row-normalized heatmap: ≈
- Ham row: 0.99 correct, 0.01 false positives
- Spam row: 0.99 correct, 0.01 false negatives

Classification report (rounded):
- Ham: precision ~0.996
"""